global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["fastapi:8000"]

  - job_name: "celery"
    static_configs:
      - targets: ["celery:5555"]
