"""initial migration2

Revision ID: 16f465da224b
Revises: 6eec5ffa83b9
Create Date: 2025-07-30 14:34:27.507277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f465da224b'
down_revision: Union[str, Sequence[str], None] = '6eec5ffa83b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('company', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'company')
    # ### end Alembic commands ###
