"""initial3

Revision ID: a77f9cbca304
Revises: 8fd3855ce404
Create Date: 2025-07-18 19:11:51.493292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography 


# revision identifiers, used by Alembic.
revision: str = 'a77f9cbca304'
down_revision: Union[str, Sequence[str], None] = '8fd3855ce404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')
    op.alter_column(
        'shifts',
        'location',
        existing_type=Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
        type_=Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
        existing_nullable=True
    )
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'acc_num',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'badge',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'badge_exp',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'ni',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'utr',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'share_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'brit_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'emergency_cntat_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'emergency_cntact_num',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'relationship_wit_cntat',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'relationship_wit_cntat',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'emergency_cntact_num',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'emergency_cntat_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'brit_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'share_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'utr',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'ni',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'badge_exp',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('users', 'badge',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('users', 'acc_num',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column(
        'shifts',
        'location',
        existing_type=Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
        type_=Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
        existing_nullable=True
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
