"""shifts added

Revision ID: cd26f1cac4f7
Revises: 9ff5d663376c
Create Date: 2025-07-23 21:44:19.941024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography 


# revision identifiers, used by Alembic.
revision: str = 'cd26f1cac4f7'
down_revision: Union[str, Sequence[str], None] = '9ff5d663376c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')
    op.add_column('shift_assignments', sa.Column('assigned_by', sa.Integer(), nullable=True))
    op.add_column('shift_assignments', sa.Column('response', sa.String(), nullable=True))
    op.add_column('shift_assignments', sa.Column('status', sa.String(), nullable=True))
    op.create_foreign_key(None, 'shift_assignments', 'users', ['assigned_by'], ['id'], ondelete='CASCADE')
    op.add_column('shifts', sa.Column('created_by', sa.Integer(), nullable=True))
    op.alter_column(
        'shifts',
        'location',
        existing_type=Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
        type_=Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
        existing_nullable=True
    )
    op.create_foreign_key(None, 'shifts', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shifts', type_='foreignkey')
    op.alter_column(
        'shifts',
        'location',
        existing_type=Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
        type_=Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
        existing_nullable=True
    )
    op.drop_column('shifts', 'created_by')
    op.drop_constraint(None, 'shift_assignments', type_='foreignkey')
    op.drop_column('shift_assignments', 'status')
    op.drop_column('shift_assignments', 'response')
    op.drop_column('shift_assignments', 'assigned_by')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    # ### end Alembic commands ###
