"""point location removed

Revision ID: e30975936c6e
Revises: cd26f1cac4f7
Create Date: 2025-07-27 15:25:12.946355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography 


# revision identifiers, used by Alembic.
revision: str = 'e30975936c6e'
down_revision: Union[str, Sequence[str], None] = 'cd26f1cac4f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')
    op.drop_index(op.f('idx_shifts_location'), table_name='shifts', postgresql_using='gist')
    op.drop_column('shifts', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'shifts',
        'location',
        existing_type=Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
        type_=Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
        existing_nullable=True
    )
    op.create_index(op.f('idx_shifts_location'), 'shifts', ['location'], unique=False, postgresql_using='gist')
    # #op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    # ### end Alembic commands ###
