"""attendance update

Revision ID: e61a196064d0
Revises: e30975936c6e
Create Date: 2025-07-27 22:19:27.503822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e61a196064d0'
down_revision: Union[str, Sequence[str], None] = 'e30975936c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')
    op.add_column('attendances', sa.Column('assign_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('attendances_shift_id_fkey'), 'attendances', type_='foreignkey')
    op.create_foreign_key(None, 'attendances', 'shift_assignments', ['assign_id'], ['id'], ondelete='CASCADE')
    op.drop_column('attendances', 'shift_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('shift_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.create_foreign_key(op.f('attendances_shift_id_fkey'), 'attendances', 'shifts', ['shift_id'], ['id'], ondelete='CASCADE')
    op.drop_column('attendances', 'assign_id')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    # ### end Alembic commands ###
