"""model choices removed

Revision ID: 9ff5d663376c
Revises: a77f9cbca304
Create Date: 2025-07-22 15:59:04.101411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography 


# revision identifiers, used by Alembic.
revision: str = '9ff5d663376c'
down_revision: Union[str, Sequence[str], None] = 'a77f9cbca304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')
    op.alter_column(
        'shifts',
        'location',
        existing_type=Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
        type_=Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
        existing_nullable=True
    )
    op.add_column('users', sa.Column('acc_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('sort_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('default_pass_changed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_pass_changed')
    op.drop_column('users', 'sort_code')
    op.drop_column('users', 'acc_name')
    op.alter_column(
        'shifts',
        'location',
        existing_type=Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
        type_=Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
        existing_nullable=True
    )
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    # ### end Alembic commands ###
